
package com.isdcm.streamingapp.services.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VideosPortService", targetNamespace = "http://spring.io/guides/gs-producing-web-service", wsdlLocation = "http://localhost:8082/ws/videos.wsdl")
public class VideosPortService
    extends Service
{

    private final static URL VIDEOSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIDEOSPORTSERVICE_EXCEPTION;
    private final static QName VIDEOSPORTSERVICE_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "VideosPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/ws/videos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIDEOSPORTSERVICE_WSDL_LOCATION = url;
        VIDEOSPORTSERVICE_EXCEPTION = e;
    }

    public VideosPortService() {
        super(__getWsdlLocation(), VIDEOSPORTSERVICE_QNAME);
    }

    public VideosPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIDEOSPORTSERVICE_QNAME, features);
    }

    public VideosPortService(URL wsdlLocation) {
        super(wsdlLocation, VIDEOSPORTSERVICE_QNAME);
    }

    public VideosPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIDEOSPORTSERVICE_QNAME, features);
    }

    public VideosPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VideosPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VideosPort
     */
    @WebEndpoint(name = "VideosPortSoap11")
    public VideosPort getVideosPortSoap11() {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "VideosPortSoap11"), VideosPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VideosPort
     */
    @WebEndpoint(name = "VideosPortSoap11")
    public VideosPort getVideosPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "VideosPortSoap11"), VideosPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIDEOSPORTSERVICE_EXCEPTION!= null) {
            throw VIDEOSPORTSERVICE_EXCEPTION;
        }
        return VIDEOSPORTSERVICE_WSDL_LOCATION;
    }

}
