
package com.isdcm.streamingapp.services.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VideosPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VideosPort {


    /**
     * 
     * @param filterVideosByTitleRequest
     * @return
     *     returns com.isdcm.streamingapp.services.soap.FilterVideosByTitleResponse
     */
    @WebMethod
    @WebResult(name = "filterVideosByTitleResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "filterVideosByTitleResponse")
    public FilterVideosByTitleResponse filterVideosByTitle(
        @WebParam(name = "filterVideosByTitleRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "filterVideosByTitleRequest")
        FilterVideosByTitleRequest filterVideosByTitleRequest);

    /**
     * 
     * @param filterVideosByAutorRequest
     * @return
     *     returns com.isdcm.streamingapp.services.soap.FilterVideosByAutorResponse
     */
    @WebMethod
    @WebResult(name = "filterVideosByAutorResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "filterVideosByAutorResponse")
    public FilterVideosByAutorResponse filterVideosByAutor(
        @WebParam(name = "filterVideosByAutorRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "filterVideosByAutorRequest")
        FilterVideosByAutorRequest filterVideosByAutorRequest);

    /**
     * 
     * @param filterVideosByYearRequest
     * @return
     *     returns com.isdcm.streamingapp.services.soap.FilterVideosByYearResponse
     */
    @WebMethod
    @WebResult(name = "filterVideosByYearResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "filterVideosByYearResponse")
    public FilterVideosByYearResponse filterVideosByYear(
        @WebParam(name = "filterVideosByYearRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "filterVideosByYearRequest")
        FilterVideosByYearRequest filterVideosByYearRequest);

    /**
     * 
     * @param getVideosRequest
     * @return
     *     returns com.isdcm.streamingapp.services.soap.GetVideosResponse
     */
    @WebMethod
    @WebResult(name = "getVideosResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getVideosResponse")
    public GetVideosResponse getVideos(
        @WebParam(name = "getVideosRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getVideosRequest")
        GetVideosRequest getVideosRequest);

}
